-- AUTO-GENERATED schema for the TEST Supabase project
-- Source: production PostgREST OpenAPI. Enums emitted as text on purpose.
-- Safe to run once on an empty project.

create table if not exists public."branches" (
  "id" uuid default gen_random_uuid() primary key,
  "name" text not null,
  "address" text,
  "created_at" timestamptz default now()
);

create table if not exists public."clients" (
  "id" uuid default gen_random_uuid() primary key,
  "name" text not null,
  "phone" text not null,
  "created_at" timestamptz default now(),
  "email" text
);

create table if not exists public."employees" (
  "id" uuid default gen_random_uuid() primary key,
  "auth_id" uuid,
  "name" text not null,
  "role" text default 'Receptionist',
  "branch_id" uuid,
  "phone" text,
  "created_at" timestamptz default now(),
  "username" text,
  "permission_dashboard" boolean default true,
  "permission_reception" boolean default true,
  "permission_work_orders" boolean default true,
  "permission_customers" boolean default true,
  "permission_reports" boolean default true,
  "permission_employees" boolean default false
);

create table if not exists public."vehicles" (
  "id" uuid default gen_random_uuid() primary key,
  "client_id" uuid,
  "make" text not null,
  "model" text not null,
  "engine_size" text,
  "plate_number" text,
  "created_at" timestamptz default now(),
  "booklet_serial" text
);

create table if not exists public."inventory" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "item_code" text not null,
  "name" text not null,
  "category" text not null,
  "purchase_price" numeric not null,
  "sell_price" numeric not null,
  "quantity" integer default 0,
  "min_quantity" integer default 5,
  "created_at" timestamptz default now(),
  "notes" text
);

create table if not exists public."warehouse_notes" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "content" text,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now()
);

create table if not exists public."suggestion_lists" (
  "key" text not null,
  "label" text not null,
  "items" jsonb not null,
  "updated_at" timestamptz default timezone('utc'::text, now()) not null,
  "branch_id" uuid not null,
  primary key ("key", "branch_id")
);

create table if not exists public."workshop_settings" (
  "id" integer generated by default as identity primary key,
  "setting_key" varchar not null,
  "setting_value" text not null
);

create table if not exists public."documents_archive" (
  "id" integer generated by default as identity primary key,
  "name" varchar not null,
  "category" varchar not null,
  "file_type" varchar not null,
  "file_size" varchar not null,
  "file_url" text,
  "created_at" timestamptz default now()
);

create table if not exists public."pos_sales" (
  "id" integer generated by default as identity primary key,
  "total_amount" numeric not null,
  "payment_method" varchar,
  "items" jsonb not null,
  "created_at" timestamptz default now()
);

create table if not exists public."inspection_reports" (
  "id" uuid default gen_random_uuid() primary key,
  "report_number" integer not null,
  "branch_id" uuid,
  "vehicle_id" uuid,
  "receptionist_id" uuid,
  "supervisor_id" uuid,
  "status" text default 'تم الاستلام',
  "odometer_reading" integer not null,
  "total_price" numeric default 0,
  "notes" text,
  "completed_at" timestamptz,
  "created_at" timestamptz default now(),
  "estimated_duration" integer default 0,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "elapsed_time" integer default 0,
  "is_delayed" boolean default false,
  "bay_number" varchar,
  "technician_id" uuid,
  "selected_services" jsonb,
  "warranty_expiry_date" timestamptz,
  "warranty_status" varchar default 'active',
  "odometer_unit" text default 'km' not null,
  "order_type" text default 'maintenance' not null,
  "technician_rating" text,
  "technician_rating_notes" text
);

create table if not exists public."payroll_records" (
  "id" integer generated by default as identity primary key,
  "emp_id" uuid,
  "salary_month" varchar not null,
  "base_salary" numeric not null,
  "absences_days" integer default 0,
  "bonus_amount" numeric default 0,
  "status" varchar default 'pending',
  "created_at" timestamptz default now()
);

create table if not exists public."inventory_transactions" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "inventory_id" uuid,
  "item_code" text,
  "item_name" text,
  "transaction_type" text not null,
  "quantity_changed" integer not null,
  "quantity_before" integer not null,
  "quantity_after" integer not null,
  "user_name" text,
  "created_at" timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public."used_parts" (
  "id" uuid default gen_random_uuid() primary key,
  "report_id" uuid,
  "inventory_id" uuid,
  "quantity" integer not null,
  "unit_price" numeric not null,
  "total_price" numeric not null,
  "created_at" timestamptz default now(),
  "part_name" text,
  "part_code" text
);

create table if not exists public."report_services" (
  "id" uuid default gen_random_uuid() primary key,
  "report_id" uuid,
  "category" text not null,
  "status" text not null,
  "notes" text,
  "service_price" numeric default 0,
  "photo_url" text,
  "created_at" timestamptz default now()
);

-- Foreign keys (added after all tables exist)
alter table public."employees" add constraint "employees_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."vehicles" add constraint "vehicles_client_id_fkey" foreign key ("client_id") references public."clients"("id") on delete set null;
alter table public."inventory" add constraint "inventory_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."warehouse_notes" add constraint "warehouse_notes_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."suggestion_lists" add constraint "suggestion_lists_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_vehicle_id_fkey" foreign key ("vehicle_id") references public."vehicles"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_receptionist_id_fkey" foreign key ("receptionist_id") references public."employees"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_supervisor_id_fkey" foreign key ("supervisor_id") references public."employees"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_technician_id_fkey" foreign key ("technician_id") references public."employees"("id") on delete set null;
alter table public."payroll_records" add constraint "payroll_records_emp_id_fkey" foreign key ("emp_id") references public."employees"("id") on delete set null;
alter table public."inventory_transactions" add constraint "inventory_transactions_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inventory_transactions" add constraint "inventory_transactions_inventory_id_fkey" foreign key ("inventory_id") references public."inventory"("id") on delete set null;
alter table public."used_parts" add constraint "used_parts_report_id_fkey" foreign key ("report_id") references public."inspection_reports"("id") on delete set null;
alter table public."used_parts" add constraint "used_parts_inventory_id_fkey" foreign key ("inventory_id") references public."inventory"("id") on delete set null;
alter table public."report_services" add constraint "report_services_report_id_fkey" foreign key ("report_id") references public."inspection_reports"("id") on delete set null;

-- report_number auto-increment (source backs it with a sequence)
create sequence if not exists public.inspection_reports_report_number_seq;
alter table public.inspection_reports alter column report_number set default nextval('public.inspection_reports_report_number_seq');
