-- AUTO-GENERATED schema for the TEST Supabase project
-- Source: production PostgREST OpenAPI. Enums emitted as text on purpose.
-- Safe to run once on an empty project.

create table if not exists public."branches" (
  "id" uuid default gen_random_uuid() primary key,
  "name" text not null,
  "address" text,
  "created_at" timestamptz default now()
);

create table if not exists public."clients" (
  "id" uuid default gen_random_uuid() primary key,
  "name" text not null,
  "phone" text not null,
  "created_at" timestamptz default now(),
  "email" text
);

create table if not exists public."employees" (
  "id" uuid default gen_random_uuid() primary key,
  "auth_id" uuid,
  "name" text not null,
  "role" text default 'Receptionist',
  "branch_id" uuid,
  "phone" text,
  "created_at" timestamptz default now(),
  "username" text,
  "permission_dashboard" boolean default true,
  "permission_reception" boolean default true,
  "permission_work_orders" boolean default true,
  "permission_customers" boolean default true,
  "permission_reports" boolean default true,
  "permission_employees" boolean default false
);

create table if not exists public."vehicles" (
  "id" uuid default gen_random_uuid() primary key,
  "client_id" uuid,
  "make" text not null,
  "model" text not null,
  "engine_size" text,
  "plate_number" text,
  "created_at" timestamptz default now(),
  "booklet_serial" text
);

create table if not exists public."inventory" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "item_code" text not null,
  "name" text not null,
  "category" text not null,
  "purchase_price" numeric not null,
  "sell_price" numeric not null,
  "quantity" integer default 0,
  "min_quantity" integer default 5,
  "created_at" timestamptz default now(),
  "notes" text
);

create table if not exists public."warehouse_notes" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "content" text,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now()
);

create table if not exists public."suggestion_lists" (
  "key" text not null,
  "label" text not null,
  "items" jsonb not null,
  "updated_at" timestamptz default timezone('utc'::text, now()) not null,
  "branch_id" uuid not null,
  primary key ("key", "branch_id")
);

create table if not exists public."workshop_settings" (
  "id" integer generated by default as identity primary key,
  "setting_key" varchar not null,
  "setting_value" text not null
);

create table if not exists public."documents_archive" (
  "id" integer generated by default as identity primary key,
  "name" varchar not null,
  "category" varchar not null,
  "file_type" varchar not null,
  "file_size" varchar not null,
  "file_url" text,
  "created_at" timestamptz default now()
);

create table if not exists public."pos_sales" (
  "id" integer generated by default as identity primary key,
  "total_amount" numeric not null,
  "payment_method" varchar,
  "items" jsonb not null,
  "created_at" timestamptz default now()
);

create table if not exists public."inspection_reports" (
  "id" uuid default gen_random_uuid() primary key,
  "report_number" integer not null,
  "branch_id" uuid,
  "vehicle_id" uuid,
  "receptionist_id" uuid,
  "supervisor_id" uuid,
  "status" text default 'تم الاستلام',
  "odometer_reading" integer not null,
  "total_price" numeric default 0,
  "notes" text,
  "completed_at" timestamptz,
  "created_at" timestamptz default now(),
  "estimated_duration" integer default 0,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "elapsed_time" integer default 0,
  "is_delayed" boolean default false,
  "bay_number" varchar,
  "technician_id" uuid,
  "selected_services" jsonb,
  "warranty_expiry_date" timestamptz,
  "warranty_status" varchar default 'active',
  "odometer_unit" text default 'km' not null,
  "order_type" text default 'maintenance' not null,
  "technician_rating" text,
  "technician_rating_notes" text
);

create table if not exists public."payroll_records" (
  "id" integer generated by default as identity primary key,
  "emp_id" uuid,
  "salary_month" varchar not null,
  "base_salary" numeric not null,
  "absences_days" integer default 0,
  "bonus_amount" numeric default 0,
  "status" varchar default 'pending',
  "created_at" timestamptz default now()
);

create table if not exists public."inventory_transactions" (
  "id" uuid default gen_random_uuid() primary key,
  "branch_id" uuid,
  "inventory_id" uuid,
  "item_code" text,
  "item_name" text,
  "transaction_type" text not null,
  "quantity_changed" integer not null,
  "quantity_before" integer not null,
  "quantity_after" integer not null,
  "user_name" text,
  "created_at" timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public."used_parts" (
  "id" uuid default gen_random_uuid() primary key,
  "report_id" uuid,
  "inventory_id" uuid,
  "quantity" integer not null,
  "unit_price" numeric not null,
  "total_price" numeric not null,
  "created_at" timestamptz default now(),
  "part_name" text,
  "part_code" text
);

create table if not exists public."report_services" (
  "id" uuid default gen_random_uuid() primary key,
  "report_id" uuid,
  "category" text not null,
  "status" text not null,
  "notes" text,
  "service_price" numeric default 0,
  "photo_url" text,
  "created_at" timestamptz default now()
);

-- Foreign keys (added after all tables exist)
alter table public."employees" add constraint "employees_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."vehicles" add constraint "vehicles_client_id_fkey" foreign key ("client_id") references public."clients"("id") on delete set null;
alter table public."inventory" add constraint "inventory_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."warehouse_notes" add constraint "warehouse_notes_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."suggestion_lists" add constraint "suggestion_lists_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_vehicle_id_fkey" foreign key ("vehicle_id") references public."vehicles"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_receptionist_id_fkey" foreign key ("receptionist_id") references public."employees"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_supervisor_id_fkey" foreign key ("supervisor_id") references public."employees"("id") on delete set null;
alter table public."inspection_reports" add constraint "inspection_reports_technician_id_fkey" foreign key ("technician_id") references public."employees"("id") on delete set null;
alter table public."payroll_records" add constraint "payroll_records_emp_id_fkey" foreign key ("emp_id") references public."employees"("id") on delete set null;
alter table public."inventory_transactions" add constraint "inventory_transactions_branch_id_fkey" foreign key ("branch_id") references public."branches"("id") on delete set null;
alter table public."inventory_transactions" add constraint "inventory_transactions_inventory_id_fkey" foreign key ("inventory_id") references public."inventory"("id") on delete set null;
alter table public."used_parts" add constraint "used_parts_report_id_fkey" foreign key ("report_id") references public."inspection_reports"("id") on delete set null;
alter table public."used_parts" add constraint "used_parts_inventory_id_fkey" foreign key ("inventory_id") references public."inventory"("id") on delete set null;
alter table public."report_services" add constraint "report_services_report_id_fkey" foreign key ("report_id") references public."inspection_reports"("id") on delete set null;

-- report_number auto-increment (source backs it with a sequence)
create sequence if not exists public.inspection_reports_report_number_seq;
alter table public.inspection_reports alter column report_number set default nextval('public.inspection_reports_report_number_seq');

-- ============================================================================
--  FUNCTIONS, RLS & RPCs  (mirrors production migrations)
-- ============================================================================

-- exec_sql: run maintenance SQL. Locked to service_role (never anon/authenticated).
create or replace function public.exec_sql(sql text) returns json
language plpgsql security definer set search_path = public as $$
begin
  execute sql;
  return json_build_object('status','success');
end; $$;
revoke all on function public.exec_sql(text) from public, anon, authenticated;
grant execute on function public.exec_sql(text) to service_role;

-- assistant_query: read-only SELECT executor for the AI assistant (service_role only).
create or replace function public.assistant_query(query_text text)
returns json language plpgsql security definer set search_path = public as $$
declare result json;
begin
  if query_text !~* '^\s*(select|with)\s' then
    raise exception 'Only read-only SELECT/WITH queries are allowed.';
  end if;
  if query_text ~* '\m(insert|update|delete|drop|alter|truncate|grant|revoke|create|comment|merge|vacuum|refresh|call|copy|reindex|cluster|attach|detach)\M' then
    raise exception 'Only read-only queries are allowed.';
  end if;
  set local statement_timeout = '10s';
  execute format(
    'select coalesce(json_agg(t), ''[]''::json) from (select * from (%s) sub limit 1000) t',
    query_text
  ) into result;
  return result;
end; $$;
revoke all on function public.assistant_query(text) from public, anon, authenticated;
grant execute on function public.assistant_query(text) to service_role;

-- Row-Level Security: enable + authenticated-only policy on every app table (anon denied).
do $$
declare t text; p record;
begin
  foreach t in array array[
    'vehicles','pos_sales','clients','suggestion_lists','employees',
    'documents_archive','branches','inspection_reports','payroll_records',
    'used_parts','inventory_transactions','report_services','workshop_settings',
    'inventory','warehouse_notes'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    for p in select policyname from pg_policies where schemaname='public' and tablename=t
    loop execute format('drop policy if exists %I on public.%I;', p.policyname, t); end loop;
    execute format('create policy %I on public.%I for all to authenticated using (true) with check (true);',
      'authenticated_all_access', t);
  end loop;
end $$;

-- Public booklet (QR/barcode) lookup for anonymous customers.
create or replace function public.get_public_booklet(p_serial text)
returns jsonb language sql stable security definer set search_path = public as $$
  select case when v.id is null then null else jsonb_build_object(
    'vehicle', jsonb_build_object(
      'id', v.id, 'make', v.make, 'model', v.model,
      'plate_number', v.plate_number, 'engine_size', v.engine_size,
      'booklet_serial', v.booklet_serial,
      'clients', case when c.id is null then null
                 else jsonb_build_object('id', c.id, 'name', c.name, 'phone', c.phone) end
    ),
    'reports', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', r.id, 'report_number', r.report_number, 'status', r.status,
        'total_price', r.total_price, 'selected_services', r.selected_services,
        'odometer_reading', r.odometer_reading, 'created_at', r.created_at,
        'branches', case when b.id is null then null else jsonb_build_object('name', b.name) end,
        'receptionist', case when e.id is null then null else jsonb_build_object('name', e.name) end
      ) order by r.created_at desc)
      from inspection_reports r
      left join branches b on b.id = r.branch_id
      left join employees  e on e.id = r.receptionist_id
      where r.vehicle_id = v.id
    ), '[]'::jsonb)
  ) end
  from vehicles v
  left join clients c on c.id = v.client_id
  where v.booklet_serial = p_serial
  limit 1;
$$;
revoke all     on function public.get_public_booklet(text) from public;
grant  execute on function public.get_public_booklet(text) to anon, authenticated;
